### ISSUE TITLE
Ability to use your own dataset

### ISSUE THREAD

**Issue by joc32** [facebookresearch/SEAL_OGB#1]
Hi @muhanzhang , thanks for sharing this great utility. I managed to run script on the default dataset 'ogbl-collab', but the point is to use own datasets. Seems that the object SEALDataset requires the dataset object to contain a dictionary with split edges, as here is the **split_edge** variable. 

`dataset = PygLinkPropPredDataset(name=args.dataset)`
`data = dataset[0]`
`split_edge = dataset.get_edge_split()`

`train_dataset = eval('SEALDataset')(`
    `'/.', `
    `data, `
    `split_edge, `
    `num_hops=args.num_hops, `
    `percent=args.train_percent, `
    `split='train', `
    `use_coalesce=use_coalesce, `
    `node_label=args.node_label, `
    `ratio_per_hop=args.ratio_per_hop, `
    `max_nodes_per_hop=args.max_nodes_per_hop, )`

I looked into the code of PygLinkPropPredDataset from ogb, however the  get_edge_split() method just loads the already 'preprocessed' train, test and val splits. Could you please modify the script in order for us users to process own datasets from networkx graph object, or give a hint which splitter utility to use?

**Comment by muhanzhang** [comment]
Ok. I will implement a custom data splitter for reading PyG datasets such as Cora.

**Comment by joc32** [comment]
If it helps, you can take a look at Stellargraph's edge splitter. I tried using it for usair dataset but haven't been able to get it working.

[https://stellargraph.readthedocs.io/en/stable/demos/link-prediction/gcn-link-prediction.html](url)
[https://stellargraph.readthedocs.io/en/latest/_modules/stellargraph/data/edge_splitter.html](url)

`edge_splitter_test = EdgeSplitter(G)`
`# Randomly sample a fraction p=0.1 of all positive links, and same number of negative links, from G, and obtain the`
`# reduced graph G_test with the sampled links removed:`
`G_test, edge_ids_test, edge_labels_test = edge_splitter_test.train_test_split(p=0.1, method="global", keep_connected=True)`

**Comment by muhanzhang** [comment]
I have added support for Planetoid datasets, such as Cora and CiteSeer. You can replace the Planetoid dataset with your own. Let me know if you have additional questions!

**Comment by joc32** [comment]
Trying it out at the moment, Facebook dataset from your NIPS paper takes around 97GB of RAM in order to be processed. Are there any ways how to decrease the RAM usage except setting the number of hops to 1?

**Comment by muhanzhang** [comment]
For the first question, you can set "--dynamic_train --dynamic_val --dynamic_test" to turn preprocessing subgraphs into dynamic processing on the fly. But this requires more CPU usages and is slower than preprocessing, thus is recommended only when your RAM cannot hold the preprocessing. For the second question, the building of SEALDataset (non-dynamic version) does not support multiple CPUs because PyG's InMemoryDataset does not support parallel preprocessing currently. But if you use "--dynamic_train" etc., you can set "--num_workers" to the maximum threads your machine supports to accelerate the dynamic subgraph extraction process.

**Comment by joc32** [comment]
Just tried Facebook on a machine with 192GB RAM and 100GB disk space, however the kernel crashed after building of the test dataset. RAM usage peaked at 50%. Might try with Dynamic SEAL dataset builder if I do not find the reason for crashing.

**Comment by muhanzhang** [comment]
You may retry again without using dynamic dataset. This time since the train and valid datasets have been created, they won't take additional memory for creating the datasets, and then generating the test dataset might be feasible with 192GB RAM. There is some gabbage not collected completely during the dataset generation. When all datasets are generated, you can terminate the program and restart it. Then you will find the actual memory cost for running on the generated datasets is much smaller.

**Comment by joc32** [comment]
At the end, I solved it by downsampling the graphs and achieved very similar results. Thanks for your help, much appreciated!

**Comment by muhanzhang** [comment]
> At the end, I solved it by downsampling the graphs and achieved very similar results. Thanks for your help, much appreciated!

Hi @joc32, I am sorry that I just found a bug when using custom datasets. The bug was because I didn't filter out validation/test edges from the input graph when extracting subgraphs. This has been fixed in the latest version. You may need to rerun your experiments to get the true performances. This doesn't affect the OGB datasets though.
