### ISSUE TITLE
About Planetoid edge_index utilization

### ISSUE THREAD

**Issue by bits-glitch** [facebookresearch/SEAL_OGB#18]
Hi!

Thank you again for the flexible and interesting implementation of SEAL and the possibility of using custom datasets! I really enjoy it!

In the [seal implementation,](https://github.com/facebookresearch/SEAL_OGB/blob/master/seal_link_pred.py) you are using the Planetoid dataset. May I ask why you are replacing the edge_index by `split_edge['train']['edge'].t()`, cf. [edge index](https://github.com/facebookresearch/SEAL_OGB/blob/e94e4a464965619bed3a61854a7de35e1cb3d391/seal_link_pred.py#L406). Is this line specific to the Planetoid dataset?

**Comment by muhanzhang** [comment]
Hi! This is because after data splitting, some edges of the original network are regarded as validation/testing links. During training, these links should not appear in the observed graph. 

This is specific to Planetoid (custom) datasets, because OGB datasets have pre-specified train/val/test splits as well as an observed graph (need not be exactly the training links).

**Comment by muhanzhang** [comment]
Yes. The line you pointed to did the edge splitting for custom Planetoid-like datasets. After this step, the custom dataset has the same format as OGB.

**Comment by bits-glitch** [comment]
Thank you! Can you tell me why this step `data.edge_index = split_edge['train']['edge'].t()` is omitted for the ogbl-* datasets? If I understand the datasets correctly, the ogb datasets contain the complete edge_index, not only the subsets of the train index as edge_index?

**Comment by muhanzhang** [comment]
Because the OGB datasets already have pre-specified train/test/val splits, and you can use `dataset.get_edge_split()` to retrieve it from `dataset`. In contrast, you need to do the splitting for custom datasets yourself using `do_edge_split()`. The OGB datasets have a `data = dataset[0]` which contains the observed network. Uinsg `dataset.get_edge_split()` you can also get its train/val/test edge splits. The train edges are subset of the observed network.

**Comment by bits-glitch** [comment]
Thank you very much for the explanation! Now, I have finally understood why you do not apply `data.edge_index = split_edge['train']['edge'].t()` to the ogb datasets. I discovered that the edge_index in the ogb_datasets is already reduced (i.e. it already only contains training edges, and not all edges of the complete graph), which I was not aware of. 

For example, if we take ogbl-ddi, we get:

- Train Split Edge Shape torch.Size([1067911, 2])
- Test Split Edge Shape torch.Size([133489, 2])
- Valid Split Shape torch.Size([133489, 2])

If I print the data object after `data = dataset[0]`, I get the following result:
Data(edge_index=[2, 2135822]) --> 2135822 / 2 = 1067911 (directed links), thus containing only the training links.

Thanks again for the explanation!
