### ISSUE TITLE
Question about input parameter

### ISSUE THREAD

**Issue by vymao** [facebookresearch/SEAL_OGB#2]
Hi, 

I was wondering what exactly the `--train_node_embedding` parameter is for? What else besides the DRNL label and input node feature is inputted into the DCGNN?

**Comment by muhanzhang** [comment]
If you append `--train_node_embedding`, an additional unique embedding per node id is concatenated with DRNL label and node feature before fed to a GNN, and is trained together with GNN parameters. By default it is disabled, because it is not observed to improve SEAL's performance while making it not inductive.

**Comment by vymao** [comment]
I see, thanks. And do you retrain on the validation edge set to test on the final test eedge set?

**Comment by muhanzhang** [comment]
For ogbl-collab, after we determined all the hyperparameters, we included validation edges in the input graph and retrain the model. This is as suggested by https://ogb.stanford.edu/docs/leader_rules/. For other datasets, we don't use validation edges in training.
