### ISSUE TITLE
Question regarding the training time.

### ISSUE THREAD

**Issue by VeritasYin** [facebookresearch/SEAL_OGB#5]
Hi, thanks for sharing the code.

I was wondering how long it generally will take to train a model from scratch? I understand it depends on computational power of servers. In this case, what kind of hardware configuration works the best for training SEAL on OGB tasks?

I'm using the default parameters to test the model on 'ogbl-citation'. Each training epoch takes around 4.5 hours on a server with E5-2660 (10 physical cores), 264GB memory and Tesla P100. Does the code perform normal under this setting? ?

**Comment by muhanzhang** [comment]
Hi! On ogbl-citation, the default command is changed a bit after we support directed graphs. Sorry I just updated the repo. Basically now we only need 1-hop subgraphs instead of 2, because we can query neighbors in directed graphs from both directions. You may try the updated command, which should take around 1 to 2 hours per epoch with your configuration. The new command also results in 2 percent better performance, leading to a 87.65% final test MRR.
