### ISSUE TITLE
SEAL inferencing on a Raspberry Pi

### ISSUE THREAD

**Issue by seekingdeep** [facebookresearch/SEAL_OGB#8]
@muhanzhang Hi there,
- Can SEAL inference on an arm based device such as a Raspberry Pi with 1GB of ram?
- Does inferencing a SEAL model for link prediction requires alot of ram, time and cpu?
- Does training a SEAL model for link prediction require alot of ram, when my dataset consists of 1,000,000 graphs, inwhich each graph have less than 150 nodes? for such dataset, how much ram do you estimate is needed?

**Comment by muhanzhang** [comment]
Hi! 

- 1GB ram seems too small, unless your graph is also small enough to fit in 1GB memory.
- Yes. All GNN models have a high demand for ram, time and cpu/gpu due to the repeated neighbor aggregation steps. SEAL is even more complex than plain GNN models due to its subgraph extraction around each link and labeling trick.
- I am not sure if I understand your problem correctly. You have 1M small graphs -- do you want to predict links in each of the 1M graphs? If so, then you only need a very small ram because each graph only has 150 nodes, and you can sequentially apply SEAL to each of these small graphs.

**Comment by seekingdeep** [comment]
- For inferencing, how long do you estimate it will take  RAM and Time to predict links in a (graph with 150 nodes)?
- Can SEAL be inferenced on an arm based device such as Raspberry Pi with 1GB?

**Comment by muhanzhang** [comment]
- I can only have a very rough estimate. My estimate is that you need ~1GB RAM and ~15s using GPU, to predict all 150*150/2 links.
- Using CPU (especially Raspberry Pi level CPU) would be significantly slower. May expect 10~20 times slower.

**Comment by seekingdeep** [comment]
Thanks!!

**Comment by seekingdeep** [comment]
@muhanzhang to predict missing links in a graph using only cpu and low ram, what do you suggest

**Comment by muhanzhang** [comment]
There are many ways to reduce the computation cost, such as using less number of GNN layers, subsampling neighbors, etc. You may also consider using remote servers for computation and using low-ram device to access remote servers.
